"""
Data models for Polymarket backtesting system.
"""
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class Side(Enum):
    YES = "yes"
    NO = "no"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"


class OrderStatus(Enum):
    PENDING = "pending"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"


class MarketStatus(Enum):
    OPEN = "open"
    CLOSED = "closed"
    RESOLVED = "resolved"


@dataclass
class Market:
    """Represents a prediction market."""
    id: str
    question: str
    category: str
    created_at: datetime
    resolution_date: Optional[datetime]
    status: MarketStatus = MarketStatus.OPEN
    resolved_outcome: Optional[Side] = None

    # Market metadata for strategy signals
    tags: list[str] = field(default_factory=list)
    related_market_ids: list[str] = field(default_factory=list)


@dataclass
class PricePoint:
    """A single price observation."""
    timestamp: datetime
    yes_price: float  # Price to buy YES (0-1)
    no_price: float   # Price to buy NO (0-1)
    yes_volume: float  # Volume traded on YES side
    no_volume: float   # Volume traded on NO side
    bid_yes: float     # Best bid for YES
    ask_yes: float     # Best ask for YES
    bid_no: float      # Best bid for NO
    ask_no: float      # Best ask for NO

    @property
    def spread_yes(self) -> float:
        return self.ask_yes - self.bid_yes

    @property
    def spread_no(self) -> float:
        return self.ask_no - self.bid_no

    @property
    def mid_yes(self) -> float:
        return (self.bid_yes + self.ask_yes) / 2

    @property
    def mid_no(self) -> float:
        return (self.bid_no + self.ask_no) / 2


@dataclass
class MarketSnapshot:
    """Complete market state at a point in time."""
    market: Market
    price: PricePoint

    # External signals (for information edge strategy)
    external_signals: dict = field(default_factory=dict)
    # e.g., {"poll_average": 0.52, "sentiment_score": 0.3, "news_volume": 15}


@dataclass
class Order:
    """A trade order."""
    id: str
    market_id: str
    side: Side
    order_type: OrderType
    quantity: float  # Number of shares
    limit_price: Optional[float] = None  # For limit orders
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = field(default_factory=datetime.now)
    filled_at: Optional[datetime] = None
    filled_price: Optional[float] = None
    filled_quantity: float = 0.0

    # Strategy metadata
    strategy_name: str = ""
    signal_strength: float = 0.0  # Confidence in the trade (0-1)


@dataclass
class Position:
    """Current position in a market."""
    market_id: str
    side: Side
    quantity: float
    average_entry_price: float
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0

    @property
    def cost_basis(self) -> float:
        return self.quantity * self.average_entry_price


@dataclass
class Trade:
    """A completed trade."""
    id: str
    order_id: str
    market_id: str
    side: Side
    quantity: float
    price: float
    timestamp: datetime
    fees: float = 0.0

    @property
    def total_cost(self) -> float:
        return self.quantity * self.price + self.fees


@dataclass
class PortfolioState:
    """Complete portfolio state at a point in time."""
    timestamp: datetime
    cash: float
    positions: dict[str, Position]  # market_id -> Position
    total_value: float
    unrealized_pnl: float
    realized_pnl: float

    @property
    def position_value(self) -> float:
        return self.total_value - self.cash


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    strategy_name: str
    market_id: str
    side: Side
    strength: float  # -1 to 1, negative means contra-signal
    suggested_size: float  # Fraction of available capital (0-1)
    timestamp: datetime
    metadata: dict = field(default_factory=dict)

    @property
    def is_buy(self) -> bool:
        return self.strength > 0


@dataclass
class BacktestConfig:
    """Configuration for a backtest run."""
    start_date: datetime
    end_date: datetime
    initial_capital: float = 10000.0
    max_position_size: float = 0.1  # Max 10% of capital per position
    transaction_fee_pct: float = 0.02  # 2% fees
    slippage_pct: float = 0.005  # 0.5% slippage
    rebalance_frequency: str = "daily"  # daily, hourly, etc.


@dataclass
class BacktestResult:
    """Results from a backtest run."""
    config: BacktestConfig
    portfolio_history: list[PortfolioState]
    trades: list[Trade]
    signals: list[StrategySignal]

    # Performance metrics
    total_return: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    win_rate: float = 0.0
    profit_factor: float = 0.0
    total_trades: int = 0

    # Strategy breakdown
    strategy_performance: dict = field(default_factory=dict)
